const newTasks: TaskType[] = [
    {
        name: "Check email",
        time: 20,
        id: "nt_001",
        color: "#ABE9CE",
        deadline: new Date(),
        isCompleted: false,
        status: "new",
    },
    {
        name: "Compare PPC agencies and make a report for Steven",
        time: 180,
        id: "nt_002",
        color: "#D8DCFF",
        deadline: new Date(),
        isCompleted: false,
        status: "new",
    },
    {
        name: "Meeting with Amanda (PR department)",
        time: 30,
        id: "nt_003",
        color: "#ABE9CE",
        deadline: new Date(),
        isCompleted: false,
        status: "new",
    },
    {
        name: "Get Patrick's approval for homepage new design",
        time: 20,
        id: "nt_004",
        color: "#D8DCFF",
        deadline: new Date(),
        isCompleted: false,
        status: "new",
    },
];
const scheduledTasks: TaskType[] = [
    {
        name: "Check email",
        time: 20,
        id: "sc_001",
        color: "#FFDFBA",
        deadline: new Date(),
        isCompleted: false,
        status: "scheduled",
    },
    {
        name: "Write a blogpost \"7 best strategies for SEO in 2020\"",
        time: 300,
        id: "sc_002",
        color: "#FEC6B7",
        deadline: new Date(),
        isCompleted: false,
        status: "scheduled",
    },
    {
        name: "New Ad copies for Manamaja",
        time: 120,
        id: "sc_003",
        color: "#D9E6A2",
        deadline: new Date(),
        isCompleted: false,
        status: "scheduled",
    },
];
const inProgressTasks: TaskType[] = [
    {
        name: "Check email",
        time: 20,
        id: "ip_001",
        color: "#FFDFBA",
        deadline: new Date(),
        isCompleted: false,
        status: "inProgress",
    },
    {
        name: "Record a video comment about last week's analytics report",
        time: 20,
        id: "ip_002",
        color: "#F2BAE1",
        deadline: new Date(),
        isCompleted: false,
        status: "inProgress",
    },
    {
        name: "Process all resumes for Content Marketer position",
        time: 60,
        id: "ip_003",
        color: "#FFDFBA",
        deadline: new Date(),
        isCompleted: false,
        status: "inProgress",
    },
];
const completedTasks: TaskType[] = [
    {
        name: "Check email",
        time: 20,
        id: "comp_001",
        color: "#F0F0F0",
        deadline: new Date(),
        isCompleted: true,
        status: "completed",
    },
    {
        name: "Weekly planning session",
        time: 45,
        id: "comp_002",
        color: "#F0F0F0",
        deadline: new Date(),
        isCompleted: true,
        status: "completed",
    },
    {
        name: "Create 5+ target audiences in Facebook for Samsung ...",
        time: 150,
        id: "comp_003",
        color: "#F0F0F0",
        deadline: new Date(),
        isCompleted: true,
        status: "completed",
    },
    {
        name: "Check FB Banner Design and give feedback",
        time: 20,
        id: "comp_004",
        color: "#F0F0F0",
        deadline: new Date(),
        isCompleted: true,
        status: "completed",
    },
    {
        name: "Check email",
        time: 20,
        id: "comp_005",
        color: "#F0F0F0",
        deadline: new Date(),
        isCompleted: true,
        status: "completed",
    },
];

export { newTasks, scheduledTasks, inProgressTasks, completedTasks }